version: '3.8'

services:
  northwind.webapi:
    image: ${DOCKER_REGISTRY-}northwindwebapi
    build:
      context: .
      dockerfile: src/Northwind.WebApi/Dockerfile
    networks:
      - northwind-net
    depends_on:
      - rabbitmq

  northwind.userregistrationhandlerservice:
    image: ${DOCKER_REGISTRY-}northwinduserregistrationhandlerservice
    build:
      context: .
      dockerfile: src/Northwind.UserRegistrationHandlerService/Dockerfile
    networks:
      - northwind-net
    depends_on:
      - rabbitmq

  northwind.userregistrationnotifier:
    image: ${DOCKER_REGISTRY-}northwinduserregistrationnotifier
    build:
      context: .
      dockerfile: src/Northwind.UserRegistrationNotifier/Dockerfile
    networks:
      - northwind-net
    depends_on:
      - rabbitmq

  northwind.userregistrationservice:
    image: ${DOCKER_REGISTRY-}northwinduserregistrationservice
    build:
      context: .
      dockerfile: src/Northwind.UserRegistrationService/Dockerfile
    networks:
      - northwind-net
    depends_on:
      - rabbitmq

  northwind.welcomeemailservice:
    image: ${DOCKER_REGISTRY-}northwindwelcomeemailservice
    build:
      context: .
      dockerfile: src/Northwind.WelcomeEmailService/Dockerfile
    networks:
      - northwind-net
    depends_on:
      - rabbitmq

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - northwind-net

# volumes:
#   rabbitmq_data:
  
networks:
  northwind-net:
    driver: bridge